 export const homeObjOne = {
     id: "about",
     lightBg: false,
     lightText: true,
     lightTextDesc: true,
     topLine: "Trena General Services",
     headline: "We deal mainly on bunker clearing",
     description: "We have access to unlimited credible sources to make your goods clearing easy, efficient and affordable without any hidden charges",
     buttonLabel: "Get started",
     imgStart: false,
     img: require("../../images/svg-1.svg").default,
     alt: "Cargo",
     dark: true,
     primary: true,
     darkText: false,
 };

export const homeObjThree = {
    id: "update",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "Trena General Services",
    headline: "Our service is top notch",
    description: "@Trena General Services we are available to service you better, we wants you to know that our service is effiecient and affordable with no hidden charges and also we process our client request within a stipulated time depending",
    buttonLabel: "Get started",
    imgStart: false,
    img: require("../../images/office.svg").default,
    alt: "Cargo",
    dark: false,
    primary: false,
    darkText: true,
};